workflows:
  android-workflow:
    name: Android APK Build
    environment:
      flutter: stable
    scripts:
      - name: Clean and get dependencies
        script: |
          cd mobile_app
          flutter clean
          flutter pub get
      - name: Build release APK
        script: |
          cd mobile_app
          flutter build apk --release
    artifacts:
      - mobile_app/build/app/outputs/flutter-apk/app-release.apk
